# Generated by Django 5.0.4 on 2024-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
